on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        env:
          XXX: false
          X_DRAFT: ${{ github.ref_name != 'main' }}
        run: |
          echo ${{ github.sha }} > Release.txt
          dir env:
          echo "1"
          $x = "5"
          echo "2"
          [bool] $draft = [System.Convert]::ToBoolean($Env:X_DRAFT)
          echo "3"
          if ($draft) {
            $Env:LINK = "Release link"
          } else {
            $Env:LINK = "Latest link"
          }
          Get-Content README.md | foreach { [Environment]::ExpandEnvironmentVariables($_) } | sc README.rendered.md
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: README.rendered.md
