on:
  workflow_dispatch:
permissions:
  contents: write
env:
  DRAFT: ${{ github.ref_name != 'main' }}
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        id: build
        env:
          XXX: false
          X_DRAFT: ${{ github.ref_name != 'main' }}
        run: |
          echo ${{ github.sha }} > Release.txt
          $minor = [int]($Env:GITHUB_REF_NAME -split "\.")[1]
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "minor=$minor"
          echo "Minor", $minor
          if ($minor % 2 -eq 0) {
            Add-Content -Path $Env:GITHUB_OUTPUT -Value "draft=0"
          } else {
            Add-Content -Path $Env:GITHUB_OUTPUT -Value "draft=1"
          }
          dir env:
          echo "1"
          $x = "5"
          echo "2"
          [bool] $draft = [System.Convert]::ToBoolean($Env:X_DRAFT)
          echo "3"
          echo $draft
          echo "4"
          if ($draft) {
            $Env:LINK = "Release link"
            echo "5"
          } else {
            $Env:LINK = "Latest link"
            echo "6"
          }
          Get-Content README.md | foreach { [Environment]::ExpandEnvironmentVariables($_) } | Set-Content README.rendered.md
          Get-ChildItem
      - name: Test
        run: cat Release.txt
        env:
          MINOR: ${{steps.build.outputs.minor}}
          DRAFT: ${{steps.build.outputs.draft}}
      - name: Release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: README.rendered.md
          draft: ${{steps.build.outputs.draft}}
