on:
  workflow_dispatch:
jobs:
  build_addon_software:
    runs-on: windows-latest
    steps:
      # - run: choco install gh
      # - run: gh version
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Get-ChildItem
          wsl --help
          .\makeimage.ps1 testubuntu
          Get-ChildItem
      - uses: actions/upload-artifact@v4
        with:
          # Name of the artifact to upload.
          # Optional. Default is 'artifact'
          name: wslimage
          path: testubuntu.tgz
          compression-level: 0
