on:
  workflow_dispatch:
jobs:
  build_addon_software:
    runs-on: windows-latest
    steps:
      # - run: choco install gh
      # - run: gh version
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer module
        shell: pwsh
        run: |
          Get-ChildItem
          wsl -l
